
- name: Build and Deploy Image to Kubernetes 
  hosts: localhost
  connection: local

  vars:
    image_name: my-compte-service 
    image_tag: latest
    dockerfile_path: './'
  
  vars_files:
    - vault.yml
  
  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        reauthorize: yes
    
    - name: Build Docker image
      docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ dockerhub_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build 
        state: present
    
    - name: Push the docker image to Docker Hub 
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local 
    
    - name: Pull Docker image (optional, for verification)
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull 
    
    
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: deployment.yml
        validate_certs: no

    - name: Apply Kubernetes Service 
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yml
        validate_certs: no
 - name: Apply Prometheus Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: prometheus-deployment.yml
        validate_certs: no

    - name: Apply Grafana Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: grafana-deployment.yml
        validate_certs: no

    - name: Wait for Prometheus to be ready
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: jenkins
        name: prometheus-deployment
      register: prometheus_deployment
      until: prometheus_deployment.resources[0].status.readyReplicas | default(0) >= 1
      retries: 10
      delay: 10

    - name: Wait for Grafana to be ready
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: jenkins
        name: grafana-deployment
      register: grafana_deployment
      until: grafana_deployment.resources[0].status.readyReplicas | default(0) >= 1
      retries: 10
      delay: 10

